### ISSUE TITLE
pegar o dia da semana da data selecionada no datapicket

### ISSUE THREAD

**Issue by brunojamelli** [BiaChacon/spaces-scheduling#11]
### Datapicket
![Captura de tela_2020-10-22_07-53-07](https://user-images.githubusercontent.com/21262825/96862406-ca06c780-143b-11eb-8ad5-80ec1d4be804.png)

### tentativa de codigo
`let x = new Date(this.date);`
`window.console.log(x.getDay());`
onde selecionei 6 de outubro no calendario, o que deveria dar o day 2, por ser uma terça feira, porem deu 1.
### método do JS a ser utilizado
`objectDate.getDay()`
que retorna um numero representando o dia da semana, por exemplo, domingo é 0, segunda é 1 ...

**Comment by BiaChacon** [comment]
![](https://cdn.discordapp.com/attachments/752956681989783584/769188242242797628/unknown.png)
