### ISSUE TITLE
Logs de ações de reservas do sistema em arquivos

### ISSUE THREAD

**Issue by BiaChacon** [BiaChacon/spaces-scheduling#36]

**Comment by brunojamelli** [comment]
A issue trata de um DAOque é responsavel por abrir um arquivo de texto de logs e escrever nele qualquer objeto que for feito POST ou PUT na api, usar JSON.stringify para converter o conteudo json para strings e chamar o metodo saveLog(content) para persistir o conteudo convertido em arquivo, para usar o método basta importar o arquivo daoLogs.js que esta no diretório utils.

**Comment by brunojamelli** [comment]
![Captura de tela_2020-12-05_21-20-58](https://user-images.githubusercontent.com/21262825/101268284-04a09700-3740-11eb-9014-e7cc7d8ca320.png)
